<?php
return array (
  34 => 
  array (
    'id' => '34',
    'catid' => '19',
    'typeid' => '0',
    'title' => '《学习简报1》',
    'style' => '',
    'thumb' => '',
    'keywords' => '简报',
    'description' => '《学习简报1》《学习简报1》《学习简报1》《学习简报1》《学习简报1》',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=19&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463474026',
    'updatetime' => '1463474056',
    'hitsid' => 'c-1-34',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '19',
    'typeid' => '0',
    'title' => '《学习简报2》',
    'style' => '',
    'thumb' => '',
    'keywords' => '简报',
    'description' => '《学习简报2》《学习简报2》《学习简报2》《学习简报2》',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=19&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463474061',
    'updatetime' => '1463474070',
    'hitsid' => 'c-1-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '19',
    'typeid' => '0',
    'title' => '《学习简报3》',
    'style' => '',
    'thumb' => '',
    'keywords' => '简报',
    'description' => '《学习简报3》《学习简报3》《学习简报3》《学习简报3》《学习简报3》',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=19&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463474074',
    'updatetime' => '1463474077',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '19',
    'typeid' => '0',
    'title' => '《学习简报4》',
    'style' => '',
    'thumb' => '',
    'keywords' => '简报',
    'description' => '《学习简报4》《学习简报4》《学习简报4》《学习简报4》',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=19&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463474086',
    'updatetime' => '1463474089',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  38 => 
  array (
    'id' => '38',
    'catid' => '19',
    'typeid' => '0',
    'title' => '《学习简报5》',
    'style' => '',
    'thumb' => '',
    'keywords' => '简报',
    'description' => '《学习简报5》《学习简报5》《学习简报5》',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=19&id=38',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463474103',
    'updatetime' => '1463474108',
    'hitsid' => 'c-1-38',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>