<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '11',
    'typeid' => '0',
    'title' => '职业能力列表2',
    'style' => '',
    'thumb' => '',
    'keywords' => '是嘎嘎是',
    'description' => '暗示过多少',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=11&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463471272',
    'updatetime' => '1463494331',
    'hitsid' => 'c-1-4',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '11',
    'typeid' => '0',
    'title' => '职业能力列表1',
    'style' => '',
    'thumb' => '',
    'keywords' => '刚撒个按个按时',
    'description' => '职业能力列表1职业能力列表1职业能力列表1',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=11&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463471279',
    'updatetime' => '1463492872',
    'hitsid' => 'c-1-5',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '11',
    'typeid' => '0',
    'title' => '职业能力列表3',
    'style' => '',
    'thumb' => '',
    'keywords' => '能力 职业',
    'description' => '撒飞洒发沙发',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=11&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472470',
    'updatetime' => '1463495101',
    'hitsid' => 'c-1-6',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  39 => 
  array (
    'id' => '39',
    'catid' => '11',
    'typeid' => '0',
    'title' => '安抚个大概发的发的发的管发',
    'style' => '',
    'thumb' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/uploadfile/2016/0517/20160517102721633.jpg',
    'keywords' => '管发',
    'description' => '',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=11&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463495229',
    'updatetime' => '1463495247',
    'hitsid' => 'c-1-39',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '11',
    'typeid' => '0',
    'title' => '职业能力列表4',
    'style' => '',
    'thumb' => '',
    'keywords' => '能力 职业',
    'description' => '213123123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=11&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472481',
    'updatetime' => '1463472487',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>