<?php
return array (
  21 => 
  array (
    'id' => '21',
    'catid' => '15',
    'typeid' => '0',
    'title' => '优秀人物1',
    'style' => '',
    'thumb' => '',
    'keywords' => '人物',
    'description' => '暗示法萨芬撒发萨法',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=15&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472598',
    'updatetime' => '1463473920',
    'hitsid' => 'c-1-21',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '15',
    'typeid' => '0',
    'title' => '优秀人物2',
    'style' => '',
    'thumb' => '',
    'keywords' => '人物',
    'description' => '123123123123321',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=15&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472605',
    'updatetime' => '1463472608',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '15',
    'typeid' => '0',
    'title' => '优秀人物3',
    'style' => '',
    'thumb' => '',
    'keywords' => '人物',
    'description' => '214124124124214',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=15&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472611',
    'updatetime' => '1463472614',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  24 => 
  array (
    'id' => '24',
    'catid' => '15',
    'typeid' => '0',
    'title' => '优秀人物4',
    'style' => '',
    'thumb' => '',
    'keywords' => '人物',
    'description' => '125125125215125',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=15&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472617',
    'updatetime' => '1463472620',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '15',
    'typeid' => '0',
    'title' => '优秀人物5',
    'style' => '',
    'thumb' => '',
    'keywords' => '人物',
    'description' => '1243125412515',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=15&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472623',
    'updatetime' => '1463472626',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>