<?php
return array (
  18 => 
  array (
    'id' => '18',
    'catid' => '14',
    'typeid' => '0',
    'title' => '他山之石2',
    'style' => '',
    'thumb' => '',
    'keywords' => '他山之石2',
    'description' => '123123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=14&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472575',
    'updatetime' => '1463473651',
    'hitsid' => 'c-1-18',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '14',
    'typeid' => '0',
    'title' => '他山之石4',
    'style' => '',
    'thumb' => '',
    'keywords' => '他山之石4',
    'description' => '1241251251251',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=14&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472587',
    'updatetime' => '1463473915',
    'hitsid' => 'c-1-20',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '14',
    'typeid' => '0',
    'title' => '他山之石1',
    'style' => '',
    'thumb' => '',
    'keywords' => '他山之石1',
    'description' => '说法是分散按时',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=14&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472568',
    'updatetime' => '1463472572',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '14',
    'typeid' => '0',
    'title' => '他山之石3',
    'style' => '',
    'thumb' => '',
    'keywords' => '他山之石3',
    'description' => '12312321123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=14&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472581',
    'updatetime' => '1463472584',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>