<?php
return array (
  44 => 
  array (
    'id' => '44',
    'catid' => '22',
    'typeid' => '0',
    'title' => '《学习剪报2》',
    'style' => '',
    'thumb' => '',
    'keywords' => '剪报',
    'description' => '《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》《学习剪报2》   ',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=22&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463540145',
    'updatetime' => '1463540279',
    'hitsid' => 'c-1-44',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  43 => 
  array (
    'id' => '43',
    'catid' => '22',
    'typeid' => '0',
    'title' => '《学习剪报1》',
    'style' => '',
    'thumb' => '',
    'keywords' => '剪报',
    'description' => '《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》《学习剪报1》   ',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=22&id=43',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463540129',
    'updatetime' => '1463540277',
    'hitsid' => 'c-1-43',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  45 => 
  array (
    'id' => '45',
    'catid' => '22',
    'typeid' => '0',
    'title' => '《学习剪报3》',
    'style' => '',
    'thumb' => '',
    'keywords' => '剪报',
    'description' => '《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》《学习剪报3》   ',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=22&id=45',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463540158',
    'updatetime' => '1463540273',
    'hitsid' => 'c-1-45',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  46 => 
  array (
    'id' => '46',
    'catid' => '22',
    'typeid' => '0',
    'title' => '《学习剪报4》',
    'style' => '',
    'thumb' => '',
    'keywords' => '剪报',
    'description' => '《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》《学习剪报4》   ',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=22&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463540169',
    'updatetime' => '1463540233',
    'hitsid' => 'c-1-46',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '22',
    'typeid' => '0',
    'title' => '《学习剪报5》',
    'style' => '',
    'thumb' => '',
    'keywords' => '剪报',
    'description' => '《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》《学习剪报5》   ',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=22&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463540213',
    'updatetime' => '1463540224',
    'hitsid' => 'c-1-47',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>