<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '12',
    'typeid' => '0',
    'title' => '学习小组3',
    'style' => '',
    'thumb' => '',
    'keywords' => '小组',
    'description' => '是飞洒发发按时',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=12&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472510',
    'updatetime' => '1463472532',
    'hitsid' => 'c-1-10',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '12',
    'typeid' => '0',
    'title' => '学习小组4',
    'style' => '',
    'thumb' => '',
    'keywords' => '小组',
    'description' => '沙发是否 23 423 234 23',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=12&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472517',
    'updatetime' => '1463473918',
    'hitsid' => 'c-1-11',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '12',
    'typeid' => '0',
    'title' => '学习小组1',
    'style' => '',
    'thumb' => '',
    'keywords' => '小组',
    'description' => '暗示法法师撒噶啥的',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=12&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472492',
    'updatetime' => '1463472976',
    'hitsid' => 'c-1-8',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '12',
    'typeid' => '0',
    'title' => '学习小组5',
    'style' => '',
    'thumb' => '',
    'keywords' => '小组',
    'description' => '123123123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=12&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472524',
    'updatetime' => '1463472528',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '12',
    'typeid' => '0',
    'title' => '学习小组2',
    'style' => '',
    'thumb' => '',
    'keywords' => '小组',
    'description' => '沙发沙发上发萨法按时',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=12&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472503',
    'updatetime' => '1463472507',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>