<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '13',
    'typeid' => '0',
    'title' => '工作案例1',
    'style' => '',
    'thumb' => '',
    'keywords' => '案例',
    'description' => '啊发顺丰安抚按时',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=13&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472536',
    'updatetime' => '1463496341',
    'hitsid' => 'c-1-13',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '13',
    'typeid' => '0',
    'title' => '工作案例4',
    'style' => '',
    'thumb' => '',
    'keywords' => '案例',
    'description' => '213123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=13&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472557',
    'updatetime' => '1463496025',
    'hitsid' => 'c-1-16',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '13',
    'typeid' => '0',
    'title' => '工作案例2',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '123123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=13&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472545',
    'updatetime' => '1463474512',
    'hitsid' => 'c-1-14',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '13',
    'typeid' => '0',
    'title' => '工作案例3',
    'style' => '',
    'thumb' => '',
    'keywords' => '案例',
    'description' => '23123123',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=13&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472550',
    'updatetime' => '1463473098',
    'hitsid' => 'c-1-15',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>