<?php
return array (
  31 => 
  array (
    'id' => '31',
    'catid' => '18',
    'typeid' => '0',
    'title' => '两学一做2',
    'style' => '',
    'thumb' => '',
    'keywords' => '两学一做2',
    'description' => '两学一做2两学一做2两学一做2',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=18&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472696',
    'updatetime' => '1463472701',
    'hitsid' => 'c-1-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '18',
    'typeid' => '0',
    'title' => '两学一做3',
    'style' => '',
    'thumb' => '',
    'keywords' => '两学一做3',
    'description' => '2414125215125',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=18&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472704',
    'updatetime' => '1463472709',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '18',
    'typeid' => '0',
    'title' => '两学一做4',
    'style' => '',
    'thumb' => '',
    'keywords' => '两学一做4',
    'description' => '214125125125',
    'posids' => '0',
    'url' => 'http://127.0.0.1/xsc_fdyzt/fdyzt/index.php?m=content&c=index&a=show&catid=18&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1463472712',
    'updatetime' => '1463472715',
    'hitsid' => 'c-1-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>